name: latkuis_124240137
description: "Aplikasi katalog menu Gacoan untuk Latihan Kuis Praktikum Pemrograman Mobile SI-G."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.9

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
